package TimetableReg;


import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.date;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.Timer;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.util.regex.Matcher;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ayub
 */
public class Timetable extends javax.swing.JFrame {

    Connection con = null;
    PreparedStatement pst = null;
    /**
     * Creates new form Timetable
     */
    public Timetable() {
        initComponents();
         
      
    }
        
      
    
       

        
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelSubjects = new javax.swing.JPanel();
        jLabelHeading = new javax.swing.JLabel();
        jLabelSubHeading = new javax.swing.JLabel();
        jLabelSubjects = new javax.swing.JLabel();
        jLabelLecName = new javax.swing.JLabel();
        jLabelTime = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        jTextField_name = new javax.swing.JTextField();
        jTextTime = new javax.swing.JTextField();
        jTextEmail = new javax.swing.JTextField();
        jButtonRegister = new javax.swing.JButton();
        jButtonReset = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jComboSubjects = new javax.swing.JComboBox<>();
        jLabelDate = new javax.swing.JLabel();
        jTextDate = new javax.swing.JTextField();
        jButtonExit = new javax.swing.JButton();
        jButtonMinimize = new javax.swing.JButton();
        jLabelee = new javax.swing.JLabel();
        jLabelaa = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelHeading.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabelHeading.setText("NEW TIME TABLE REGISTRATION");

        jLabelSubHeading.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelSubHeading.setForeground(new java.awt.Color(0, 102, 102));
        jLabelSubHeading.setText("SIPSEWANA");

        jLabelSubjects.setText("Subject");

        jLabelLecName.setText("Lecturer Name");

        jLabelTime.setText("Time");

        jLabelEmail.setText("Email");

        jTextField_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_nameActionPerformed(evt);
            }
        });
        jTextField_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_nameKeyPressed(evt);
            }
        });

        jTextTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextTimeActionPerformed(evt);
            }
        });

        jTextEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextEmailActionPerformed(evt);
            }
        });
        jTextEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextEmailKeyReleased(evt);
            }
        });

        jButtonRegister.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonRegister.setText("Register");
        jButtonRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegisterActionPerformed(evt);
            }
        });

        jButtonReset.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonReset.setText("Reset");
        jButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetActionPerformed(evt);
            }
        });

        jButtonCancel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jComboSubjects.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sinhala", "English", "Science", "Mathematics", "History", " " }));
        jComboSubjects.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboSubjectsActionPerformed(evt);
            }
        });

        jLabelDate.setText("Day");

        jTextDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextDateActionPerformed(evt);
            }
        });

        jButtonExit.setText("X");
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });
        jButtonExit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonExitKeyPressed(evt);
            }
        });

        jButtonMinimize.setText("-");
        jButtonMinimize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMinimizeActionPerformed(evt);
            }
        });

        jLabelee.setText(" ");

        jLabelaa.setText(" ");

        javax.swing.GroupLayout jPanelSubjectsLayout = new javax.swing.GroupLayout(jPanelSubjects);
        jPanelSubjects.setLayout(jPanelSubjectsLayout);
        jPanelSubjectsLayout.setHorizontalGroup(
            jPanelSubjectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSubjectsLayout.createSequentialGroup()
                .addGroup(jPanelSubjectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelSubjectsLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanelSubjectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelLecName)
                            .addComponent(jLabelTime)
                            .addComponent(jLabelEmail)
                            .addComponent(jLabelSubjects)
                            .addComponent(jLabelDate))
                        .addGap(40, 40, 40)
                        .addGroup(jPanelSubjectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextEmail)
                            .addComponent(jTextTime)
                            .addComponent(jTextDate)
                            .addComponent(jTextField_name)
                            .addComponent(jComboSubjects, 0, 282, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelee, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelSubjectsLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jButtonRegister)
                        .addGap(118, 118, 118)
                        .addComponent(jButtonReset)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonCancel)))
                .addGap(18, 18, 18)
                .addComponent(jLabelaa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSubjectsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelHeading)
                .addGap(105, 105, 105))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSubjectsLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanelSubjectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSubjectsLayout.createSequentialGroup()
                        .addComponent(jButtonMinimize)
                        .addGap(1, 1, 1)
                        .addComponent(jButtonExit))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSubjectsLayout.createSequentialGroup()
                        .addComponent(jLabelSubHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(226, 226, 226))))
        );
        jPanelSubjectsLayout.setVerticalGroup(
            jPanelSubjectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSubjectsLayout.createSequentialGroup()
                .addGroup(jPanelSubjectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonExit, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonMinimize))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelSubHeading)
                .addGap(23, 23, 23)
                .addGroup(jPanelSubjectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSubjects)
                    .addComponent(jComboSubjects, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelSubjectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLecName)
                    .addComponent(jTextField_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelSubjectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDate))
                .addGap(18, 18, 18)
                .addGroup(jPanelSubjectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTime))
                .addGap(18, 18, 18)
                .addGroup(jPanelSubjectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEmail)
                    .addComponent(jLabelee)
                    .addComponent(jLabelaa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelSubjectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonCancel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonRegister, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonReset, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelSubjects, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelSubjects, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_nameActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextField_nameActionPerformed

    private void jTextTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextTimeActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextTimeActionPerformed

    private void jButtonRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegisterActionPerformed
        // TODO add your handling code here:
        String Lecname=jTextField_name.getText();
        
        if(Lecname.equals("")){
            JOptionPane.showMessageDialog(null, "Enter Your Name");
            }
        
        
        if(Validation()){
                try {
            String query = " INSERT INTO `student_management`(`subject`, `name`, `date`, `time`, `email`)  VALUES (?, ?, ?, ?, ?)";
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/student_management_system", "root", "");
            pst = con.prepareStatement(query);
            pst.setString(1,jComboSubjects.getSelectedItem().toString());
            pst.setString(2,jTextField_name.getText());
            pst.setString(3,jTextDate.getText());
            pst.setString(4,jTextTime.getText());
            pst.setString(5,jTextEmail.getText());
            
            pst.executeLargeUpdate();
            JOptionPane.showMessageDialog(null, "Successful");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
        }else{
            JOptionPane.showMessageDialog(null, "Failed");}
    }//GEN-LAST:event_jButtonRegisterActionPerformed

    
    private void jComboSubjectsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboSubjectsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboSubjectsActionPerformed

    private void jTextEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextEmailActionPerformed
        // TODO add your handling code here:
    
    }//GEN-LAST:event_jTextEmailActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetActionPerformed
        // TODO add your handling code here:
        jComboSubjects.setSelectedItem("Sinhala");
        jTextField_name.setText("");
        jTextTime.setText("");
        jTextEmail.setText("");
        jTextDate.setText("");
    }//GEN-LAST:event_jButtonResetActionPerformed

    private void jTextField_nameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_nameKeyPressed
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(Character.isLetter(c)||Character.isWhitespace(c)||Character.isISOControl(c)){
            jTextField_name.setEditable(true);
        }
        else
        {
            jTextField_name.setEditable(false);
        }
    }//GEN-LAST:event_jTextField_nameKeyPressed

    private void jTextEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextEmailKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextEmailKeyReleased

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        // TODO add your handling code here:
        ActionListener al = new ActionListener() { 
            @Override 
            public void actionPerformed(ActionEvent e) { 
                System. exit(0); } }; 
                jButtonExit. addActionListener(al);
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jButtonMinimizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMinimizeActionPerformed
        // TODO add your handling code here:
        ActionListener al = new ActionListener() { 
            @Override 
            public void actionPerformed(ActionEvent e) { 
                setState(Timetable.ICONIFIED); } }; 
                jButtonMinimize. addActionListener(al);
    }//GEN-LAST:event_jButtonMinimizeActionPerformed

    private void jButtonExitKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonExitKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonExitKeyPressed

    private void jTextDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextDateActionPerformed

    public boolean Validation() {
        if ( validateemail() && validateName()) {
            JOptionPane.showMessageDialog(null, "Registered");
            return true;
        } else {
            JOptionPane.showMessageDialog(null, "Not Registered");
            return false;
        }
    }
    public boolean validateemail() {
        String email = this.jTextEmail.getText().trim();
        if (email.equals("") || email.equals(null)) {
            JOptionPane.showMessageDialog(null, "Type Your Email");
            return false;
        } else {
            String PA = "^[a-zA-Z0-9]{5,30}[@][a-zA-Z0-9]{0,10}[.][a-zA-Z]{0,3}$";
            if (!email.matches(PA)) {
                JOptionPane.showMessageDialog(null, "Enter a Valid Email");
                return false;
            } else {

                return true;
            }
        }
    }
    
    public boolean validateName() {
        String name = this.jTextField_name.getText().trim();
        if (name.equals("") || name.equals(null)) {
            JOptionPane.showMessageDialog(null, "Name cannot be empty");
            return false;
        } else {
            //String PA = "^[a-zA-Z]{5,30}[][a-zA-Z]{3,10}$";
            String PA = "^[a-z0-9_-]{5,30}$";

            if (!name.matches(PA)) {
                JOptionPane.showMessageDialog(null, "Not a valide name");
                return false;
            } else {

                return true;
            }
        }
    }

    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Timetable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Timetable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Timetable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Timetable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Timetable().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonMinimize;
    private javax.swing.JButton jButtonRegister;
    private javax.swing.JButton jButtonReset;
    private javax.swing.JComboBox<String> jComboSubjects;
    private javax.swing.JLabel jLabelDate;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelHeading;
    private javax.swing.JLabel jLabelLecName;
    private javax.swing.JLabel jLabelSubHeading;
    private javax.swing.JLabel jLabelSubjects;
    private javax.swing.JLabel jLabelTime;
    private javax.swing.JLabel jLabelaa;
    private javax.swing.JLabel jLabelee;
    private javax.swing.JPanel jPanelSubjects;
    private javax.swing.JTextField jTextDate;
    private javax.swing.JTextField jTextEmail;
    private javax.swing.JTextField jTextField_name;
    private javax.swing.JTextField jTextTime;
    // End of variables declaration//GEN-END:variables
}
