/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in 
the editor.
 */
package Subjects_TimeTables;

import Manage_TimeTables.Managetimetabledetails;
 
 

/**
 *
 * @author Ayub
 */
public class Subjectsandtimetables extends javax.swing.JFrame {

    /**
     * Creates new form Subjectsandtimetables
     */
    public Subjectsandtimetables() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelHeading = new javax.swing.JLabel();
        jLabelSubHeading = new javax.swing.JLabel();
        jButtonSubjectDetails = new javax.swing.JButton();
        jButtonTimeTableDetails = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelHeading.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabelHeading.setText("SUBJECTS AND TIME TABLES");

        jLabelSubHeading.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelSubHeading.setForeground(new java.awt.Color(0, 102, 102));
        jLabelSubHeading.setText("SIPSEWANA");

        jButtonSubjectDetails.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonSubjectDetails.setText("Manage Subject Details");
        jButtonSubjectDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubjectDetailsActionPerformed(evt);
            }
        });

        jButtonTimeTableDetails.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonTimeTableDetails.setText("Manage Time Table Details");
        jButtonTimeTableDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTimeTableDetailsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabelHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(36, 36, 36))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabelSubHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(150, 150, 150)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButtonTimeTableDetails, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                        .addComponent(jButtonSubjectDetails, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelSubHeading)
                .addGap(41, 41, 41)
                .addComponent(jButtonSubjectDetails)
                .addGap(40, 40, 40)
                .addComponent(jButtonTimeTableDetails)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSubjectDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubjectDetailsActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jButtonSubjectDetailsActionPerformed

    private void jButtonTimeTableDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTimeTableDetailsActionPerformed
        // TODO add your handling code here:
        new Managetimetabledetails().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonTimeTableDetailsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Subjectsandtimetables.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Subjectsandtimetables.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Subjectsandtimetables.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Subjectsandtimetables.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Subjectsandtimetables().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSubjectDetails;
    private javax.swing.JButton jButtonTimeTableDetails;
    private javax.swing.JLabel jLabelHeading;
    private javax.swing.JLabel jLabelSubHeading;
    // End of variables declaration//GEN-END:variables
}
